FIXUP: CHROMIUM: drm/i915/pxp: Mutisession version for Invalidate all PXP fw sessions during teardown
0-day error:

>> drivers/gpu/drm/i915/pxp/intel_pxp_tee.c:217:6: error: no previous
prototype for function 'intel_pxp_tee_end_one_fw_session'
[-Werror,-Wmissing-prototypes]

Mark the function 'intel_pxp_tee_end_one_fw_session' static.

BUG=b:247565446,b:227610040
TEST=tast run <IP> video.PlayDRM*

Change-Id: I8c622f2b6f208a0e216ad429184e1218da773e05
Signed-off-by: Aashish Sharma <shraash@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4242322
Reviewed-by: Guenter Roeck <groeck@chromium.org>
(cherry picked from commit 3961604e951e10ec5b92174a1cef592341274fc5)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4287004
Tested-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Guenter Roeck <groeck@chromium.org>