FROMGIT: ASoC: mediatek: mt8195: silence uninitialized variable warning
Smatch complains that we might hit the continue path on every iteration
through the loop.

    sound/soc/mediatek/mt8195/mt8195-mt6359-rt1019-rt5682.c:831
      mt8195_mt6359_rt1019_rt5682_card_late_probe()
    error: uninitialized symbol 'sof_comp'.

Initialize "sof_comp" to NULL to silence this warning.

Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Link: https://lore.kernel.org/r/20211208151145.GA29257@kili
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 9abc21c966619d6ead27fd48481966014fdc680f
 https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git for-next)

BUG=b:202809328
TEST=emerge-cherry sys-kernel/chromeos-kernel-5_10

Signed-off-by: Trevor Wu <trevor.wu@mediatek.com>
Change-Id: I819c1f6e6567decc8f99253d87b8c038a2ccba31
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3354773
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Tzung-Bi Shih <tzungbi@chromium.org>
Commit-Queue: Tzung-Bi Shih <tzungbi@chromium.org>
Tested-by: Tzung-Bi Shih <tzungbi@chromium.org>