FIXUP: BACKPORT: FROMLIST: drm/amdgpu: Add support for drm_privacy_screen
gcc build produces this error:

drivers/gpu/drm/amd/amdgpu/../amdgpu/amdgpu.h:41:22: error: format ‘%d’
expects argument of type ‘int’, but argument 3 has type ‘long int’
[-Werror=format=]

Changing to %ld resolves the issue.

BUG=b:204401306
TEST=clean gcc build and CQ+1

Change-Id: I3cd59a53e78c50d6e3aaade1e079751d98251923
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3553271
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>