CHROMIUM: media: platform: mtk-mdp3: depend on MTK_MMSYS
Fixes the following messages during buildtest:
ERROR: modpost: "mtk_mutex_unprepare"
[drivers/media/platform/mtk-mdp3/mtk-mdp3.ko] undefined!
ERROR: modpost: "mtk_mmsys_mdp_disconnect"
[drivers/media/platform/mtk-mdp3/mtk-mdp3.ko] undefined!
ERROR: modpost: "mtk_mutex_enable_by_cmdq"
[drivers/media/platform/mtk-mdp3/mtk-mdp3.ko] undefined!
ERROR: modpost: "mtk_mmsys_mdp_connect"
[drivers/media/platform/mtk-mdp3/mtk-mdp3.ko] undefined!
ERROR: modpost: "mtk_mutex_add_mod_by_cmdq"
[drivers/media/platform/mtk-mdp3/mtk-mdp3.ko] undefined!
ERROR: modpost: "mtk_mutex_prepare"
[drivers/media/platform/mtk-mdp3/mtk-mdp3.ko] undefined!
ERROR: modpost: "mtk_mmsys_mdp_camin_ctrl"
[drivers/media/platform/mtk-mdp3/mtk-mdp3.ko] undefined!
ERROR: modpost: "mtk_mmsys_mdp_isp_ctrl"
[drivers/media/platform/mtk-mdp3/mtk-mdp3.ko] undefined!
ERROR: modpost: "mtk_mutex_put"
[drivers/media/platform/mtk-mdp3/mtk-mdp3.ko] undefined!
ERROR: modpost: "mtk_mutex_mdp_get"
[drivers/media/platform/mtk-mdp3/mtk-mdp3.ko] undefined!

BUG=b:188567470
TEST=USE="buildtest clang" emerge-arm-generic chromeos-kernel-5_10

Signed-off-by: Tzung-Bi Shih <tzungbi@chromium.org>
Change-Id: I936604f2ceded7eb4c470f2282c4376520fdb180
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3319676
Reviewed-by: Chen-Tsung Hsieh <chentsung@chromium.org>