Revert "CHROMIUM: media: mtk-vcodec: fix possible compile error"
This reverts commit b533d5cb3f4d489476aa8a9a472b68aa54077226.

Fixes up commit 69227895ba0d ("CHROMIUM: media: mtk-vcodec: Refactor
get cap buffer and put cap buffer to disp flow").

drivers/media/platform/mtk-vcodec/vdec/vdec_h264_req_if.c:404:5:
error: use of undeclared identifier 'nal_type';

BUG=b:232131883
TEST=emerge-cherry sys-kernel/chromeos-kernel-5_10

Signed-off-by: Yunfei Dong <yunfei.dong@mediatek.com>
Change-Id: I21e7b4eb027fae6952ea3ae74e8eb03b4700d656