FIXUP: FROMLIST: spmi: mediatek: Add support for MT6873/8192
0-day reports:

spmi-mtk-pmif.c:(.text+0x356): undefined reference to
	`devm_platform_ioremap_resource_byname'

The driver depends on HAS_IOMEM.

BUG=b:188612931
TEST=Test builds

Change-Id: I02fbd47928a783fc34e1d0fa4d2a91f210178a47
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3342508
Reviewed-by: Tzung-Bi Shih <tzungbi@chromium.org>
Commit-Queue: Tzung-Bi Shih <tzungbi@chromium.org>