FIXUP: CHROMIUM: coiommu: initialize the DMA tracking table
0-day reports:

kernel/dma/coiommu.c:406:21: error: 'MAX_PHYSMEM_BITS' undeclared (first
use in this function)

Coiommu config has a dependency on sparse memory config but
the same has not been written in Kconfigs, which caused the
build to fail on architectures (like alpha) which do not
support sparse memory. Added the required dependencies in
the Kconfig files.

BUG=b:188481989
TEST=Successfully compiled the kernel on Alpha architecture

Signed-off-by: Aashish Sharma <shraash@google.com>
Change-Id: Ifa495db0016d6de14fa4bd23567b839364a82c06
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3412491
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>