UPSTREAM: ASoC: rt5682s: use 'static' qualifier
Sparse reports the following warnings:

sound/soc/codecs/rt5682s.c:44:12: error: symbol 'rt5682s_supply_names'
was not declared. Should it be static?

sound/soc/codecs/rt5682s.c:74:26: error: symbol 'rt5682s_reg' was not
declared. Should it be static?

sound/soc/codecs/rt5682s.c:2841:30: error: symbol
'rt5682s_aif1_dai_ops' was not declared. Should it be static?

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20211025185933.144327-3-pierre-louis.bossart@linux.intel.com
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 49ba5e936e1512d4c7812d433048f8909234fca0)

BUG=b:202809238
TEST=emerge-cherry sys-kernel/chromeos-kernel-5_10

Signed-off-by: Trevor Wu <trevor.wu@mediatek.com>
Change-Id: Ie7eeabe41d215a7b98e179509f3103f34e20f704
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3337749
Reviewed-by: Tzung-Bi Shih <tzungbi@chromium.org>
Tested-by: Tzung-Bi Shih <tzungbi@chromium.org>
Commit-Queue: Tzung-Bi Shih <tzungbi@chromium.org>