CHROMIUM: ASoC: AMD: acp-config: fix missing dependency on SND_SOC_ACPI
With a custom .config, the following error is thrown:

ERROR: modpost: "snd_soc_acpi_codec_list"
[sound/soc/amd/snd-acp-config.ko] undefined!

Fix by adding a clear dependency on SND_SOC_ACPI

BUG=b:208244046
TEST=SOF Audio on Guybrush platform

Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Change-Id: I2308b3ea0f0b468da60832dbef8b040eb9ddd2f3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3308588
Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>
Tested-by: Curtis Malainey <cujomalainey@chromium.org>
Commit-Queue: Curtis Malainey <cujomalainey@chromium.org>