BACKPORT: remoteproc: sysmon: fix shutdown_acked state
The latest version of sysmon_stop() starts by initializing
the sysmon->shutdown_acked variable, but then overwrites it
with an uninitialized variable later:

drivers/remoteproc/qcom_sysmon.c:551:11: error: variable 'acked' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
        else if (sysmon->ept)
                 ^~~~~~~~~~~
drivers/remoteproc/qcom_sysmon.c:554:27: note: uninitialized use occurs here
        sysmon->shutdown_acked = acked;
                                 ^~~~~

Remove the local 'acked' variable again and set the state directly.

Fixes: 5c212aaf5457 ("remoteproc: sysmon: Expose the shutdown result")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20201204193740.3162065-1-arnd@kernel.org
Signed-off-by: Bjorn Andersson <bjorn.andersson@linaro.org>

(cherry picked from commit 9d7b4a40387d0f91512a74caed6654ffa23d5ce4)

Conflicts:
   drivers/remoteproc/qcom_sysmon.c
[In 5.10, we have 9116bf84b848 ("FIXUP: FROMGIT: remoteproc: sysmon:
 Expose the shutdown result") (https://crrev.com/c/2577656) for fixing
 a 0-day issue.  However, the upstream patch 9d7b4a40387d ("remoteproc:
 sysmon: fix shutdown_acked state") removes the variable.]
[Fix the conflict by removing the variable.]

BUG=b:220261123
TEST=pass CQ

Signed-off-by: Tzung-Bi Shih <tzungbi@chromium.org>
Change-Id: Ia79836184470c38e48181aa33f16a1de575b2986
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3474098
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Guenter Roeck <groeck@chromium.org>