FIXUP: BACKPORT: FROMGIT: ASoC: rockchip: i2s: switch BCLK to GPIO
0-day errors:

>> sound/soc/rockchip/rockchip_i2s.c:62:23: error: implicit
   declaration of function 'pinctrl_select_state'
>> sound/soc/rockchip/rockchip_i2s.c:710:22: warning: assignment
   to 'struct pinctrl *' from 'int' makes pointer from integer
   without a cast
>> sound/soc/rockchip/rockchip_i2s.c:710:24: error: implicit
   declaration of function 'devm_pinctrl_get'

Include the missing header file.

BUG=b:187142184
TEST=1. Check the BCLK is turned on only 0.4 ms earlier than LRCK.
     2. Check the BCLK is turned off before LRCK.

Disallow-Recycled-Builds: test-failures
Signed-off-by: Aashish Sharma <shraash@google.com>
Change-Id: I64832964009fccdd44e4bc01359810be3c27b380
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3740246
Reviewed-by: Guenter Roeck <groeck@chromium.org>