BACKPORT: FROMLIST: drm/mediatek: add display merge start/stop API for cmdq support
Add merge start/stop API for cmdq support. The ovl_adaptor merges
are configured with each drm plane update. Need to enable/disable
merge with cmdq making sure all the settings taken effect in the
same vblank.

Signed-off-by: Nancy.Lin <nancy.lin@mediatek.com>
Reviewed-by: Chun-Kuang Hu <chunkuang.hu@kernel.org>
(am from https://patchwork.kernel.org/patch/12623971/)
(also found at https://lore.kernel.org/r/20211117085919.28691-15-nancy.lin@mediatek.com)

[fix buildtest fail]
>   CC [M]  drivers/gpu/drm/mediatek/mtk_mdp_rdma.o
> /mnt/host/source/src/third_party/kernel/v5.10/drivers/gpu/drm/mediatek/mtk_disp_merge.c:76:25:
> error: unused variable 'priv' [-Werror,-Wunused-variable]
>         struct mtk_disp_merge *priv = dev_get_drvdata(dev);
>                                ^
> 1 error generated.

BUG=b:188612925
TEST=emerge-cherry sys-kernel/chromeos-kernel-5_10

Signed-off-by: Tinghan Shen <tinghan.shen@mediatek.com>
Change-Id: I8d2bfe95722445e181ccbf38c68fe7b2c3f7b525
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3255024
Reviewed-by: Tzung-Bi Shih <tzungbi@chromium.org>
Tested-by: Tzung-Bi Shih <tzungbi@chromium.org>
Commit-Queue: Tzung-Bi Shih <tzungbi@chromium.org>