BACKPORT: ath11k: Fix uninitialized symbol 'rx_buf_sz'
Add missing else statement in ath11k_dp_rx_process_mon_status()
to fix below smatch warnings,
    drivers/net/wireless/ath/ath11k/dp_rx.c:3105
    ath11k_dp_rx_process_mon_status()
    error: uninitialized symbol 'rx_buf_sz'.

Fixes: ab18e3bc1c13 ("ath11k: Fix pktlog lite rx events")

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Anilkumar Kolli <quic_akolli@quicinc.com>
Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
Link: https://lore.kernel.org/r/1642605793-13518-1-git-send-email-quic_akolli@quicinc.com

(cherry picked from commit dca857f07dc14c923a3c47965e771f435807b39c)

Conflicts:
   drivers/net/wireless/ath/ath11k/dp_rx.c
[ Different line numbers.  See b/227130625#comment3. ]

BUG=b:227130625
BUG=b:205920109
TEST=for arch in amd64-generic arm64-generic; do \
	USE=buildtest emerge-"${arch}" chromeos-kernel-5_10; \
     done

Signed-off-by: Tzung-Bi Shih <tzungbi@chromium.org>
Change-Id: I487ae5db724b07de3bbb67041d961e30a4be98aa
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3555508
Reviewed-by: Guenter Roeck <groeck@chromium.org>