CHROMIUM: media: mtk-vcodec: fix possible compile error
Fixes up commit 69227895ba0d ("CHROMIUM: media: mtk-vcodec: Refactor
get cap buffer and put cap buffer to disp flow").

drivers/media/platform/mtk-vcodec/vdec/vdec_h264_req_if.c:404:5:
error: use of undeclared identifier 'nal_type';

BUG=b:189300514
BUG=b:206804303
TEST=emerge-cherry chromeos-kernel-5_10

Signed-off-by: Tzung-Bi Shih <tzungbi@chromium.org>
Change-Id: I687241e5f29db228550084988f4afbba92ee95c4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3297568
Commit-Queue: Hsin-Yi Wang <hsinyi@chromium.org>
Reviewed-by: Hsin-Yi Wang <hsinyi@chromium.org>