BACKPORT: FROMLIST: drm/mediatek: add display merge async reset control
Add merge async reset control in mtk_merge_stop. Async hw doesn't do self
reset on each sof signal(start of frame), so need to reset the async to
clear the hw status for the next merge start.

Signed-off-by: Nancy.Lin <nancy.lin@mediatek.com>
(am from https://patchwork.kernel.org/patch/12624005/)
(also found at https://lore.kernel.org/r/20211117085919.28691-17-nancy.lin@mediatek.com)

[fix buildtest fail]
>   CC [M]  drivers/gpu/drm/mediatek/mtk_disp_merge.o
> /mnt/host/source/src/third_party/kernel/v5.10/drivers/gpu/drm/mediatek/mtk_disp_merge.c:82:6:
> error: use of undeclared identifier 'priv'
>         if (priv->async_clk)
>             ^
> 1 error generated.

BUG=b:188612925
TEST=emerge-cherry sys-kernel/chromeos-kernel-5_10

Signed-off-by: Tinghan Shen <tinghan.shen@mediatek.com>
Change-Id: Ifc591fc30d75ae8ca0d94ec96362d65242fb4fec
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3295653
Reviewed-by: Tzung-Bi Shih <tzungbi@chromium.org>
Tested-by: Tzung-Bi Shih <tzungbi@chromium.org>
Commit-Queue: Tzung-Bi Shih <tzungbi@chromium.org>