CHROMIUM: iwl7000: mac80211: conditional config check causes build failure
Incorrectly placed #endif from #if CFG80211_VERSION >= KERNEL_VERSION(9,9,9)
causes a build failure when building 'make allmodconfig' outside of chroot:

drivers/net/wireless/iwl7000/mac80211/util.c: In function ‘ieee80211_ie_build_he_oper’:
include/asm-generic/bug.h:119:13: error: statement will never be executed [-Werror=switch-unreachable]
  119 |         int __ret_warn_on = !!(condition);                              \
        |             ^~~~~~~~~~~~~
        drivers/net/wireless/iwl7000/mac80211/util.c:3295:17: note: in expansion of macro ‘WARN_ON’
         3295 |                 WARN_ON(1);

Move the #endif down a few lines to include the entire added case.

BUG:b:218213801
TEST=Build allmodconfig outside chroot.

Change-Id: Iab054aac05e899f240e8e364334c07d1af2b02b2
Signed-off-by: Martin Faltesek <mfaltesek@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3439558
Reviewed-by: Guenter Roeck <groeck@chromium.org>