FIXUP: UPSTREAM: KVM: x86: Use __try_cmpxchg_user() to emulate atomic accesses
0-day errors:

>> arch/x86/kvm/x86.c:6504:7: error: expected ')'
     r = emulator_try_cmpxchg_user(u8, hva, old, new);
         ^
   arch/x86/kvm/x86.c:6459:3: note: expanded from macro
   'emulator_try_cmpxchg_user'
     (__try_cmpxchg_user((t __user *)(ptr),
      ^
   arch/x86/include/asm/uaccess.h:645:11: note: expanded
   from macro '__try_cmpxchg_user'
     __ret = !unsafe_try_cmpxchg_user(_ptr, _oldp, _nval, _label);
              ^
   arch/x86/include/asm/uaccess.h:622:18: note: expanded
   from macro 'unsafe_try_cmpxchg_user'
     case 1: __ret = __try_cmpxchg_user_asm("b", "q",
                     ^
   arch/x86/include/asm/uaccess.h:467:8: note: expanded from
   macro '__try_cmpxchg_user_asm'
     _ASM_EXTABLE_TYPE_REG(1b, 2b, EX_TYPE_EFAULT_REG,
     ^

The compilation error occurs because macro '_ASM_EXTABLE_TYPE_REG' is
undefined. Pick the definiton of this macro from upstream (commit
4b5305decc84).

BUG=b:242657184,b:227610040
TEST=POC

Signed-off-by: Aashish Sharma <shraash@google.com>
Change-Id: Iad1860311656265394628df37b4cadd54f75b409
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3837716
Reviewed-by: Guenter Roeck <groeck@chromium.org>