UPSTREAM: ASoC: cs35l41: Fix undefined reference to core functions
Auto select core driver if i2c or spi bus drivers are
selected

Fixes: a5e0091d62ab ("ASoC: cs35l41: Fix link problem")

Signed-off-by: Lucas Tanure <tanureal@opensource.cirrus.com>
Reported-by: kernel test robot <lkp@intel.com>
Link: https://lore.kernel.org/r/20211201180004.1402156-2-tanureal@opensource.cirrus.com
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 0695ad92fe1a0bb7697eb92c6a145a73c5ab0e24)

BUG=b:186972464
TEST=ODM tests audio function on Vell

Signed-off-by: Brent Lu <brent.lu@intel.com>
Change-Id: Ia4e30e943d60b60abc7b88f212fb7f565cd9dc3e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3390974
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Tested-by: Shon Wang <shon.wang@quanta.corp-partner.google.com>
Reviewed-by: Terry Cheong <htcheong@chromium.org>
Commit-Queue: Terry Cheong <htcheong@chromium.org>