FIXUP: BACKPORT: isystem: trim/fixup stdarg.h and other headers
0-day errors:

>> arch/um/include/shared/irq_user.h:18:2: error:
unknown type name 'bool'

Included <stdbool.h> header file to irq_user.h which got
removed in a previous cherry-pick.

BUG=b:184895604
TEST=Manual connectivity/traffic tests on Brya

Signed-off-by: Aashish Sharma <shraash@google.com>
Change-Id: I752c79e7fbd0df65836de2533dd997a9292f1325
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3529588
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>