Revert "UPSTREAM: x86/uaccess: Implement macros for CMPXCHG on user addresses"
This reverts commit 086c785972495f6c939bcb5ac4c40256fc82d7c1.

Reason for revert: Fix build error:
ld: arch/x86/kvm/x86.o:(__ex_table+0xb0): undefined reference to
`EX_TYPE_EFAULT_REG'
ld: arch/x86/kvm/x86.o:(__ex_table+0xbc): undefined reference to
`EX_TYPE_EFAULT_REG'
ld: arch/x86/kvm/x86.o:(__ex_table+0xc8): undefined reference to
`EX_TYPE_EFAULT_REG'
ld: arch/x86/kvm/x86.o:(__ex_table+0xd4): undefined reference to
`EX_TYPE_EFAULT_REG'

BUG=b:242431919
TEST=CQ

Change-Id: I74414a7f41afd453b0061a4536806475356468c3
Signed-off-by: Zubin Mithra <zsm@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4376821
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Tested-by: Zubin Mithra <zsm@chromium.org>
Commit-Queue: Zubin Mithra <zsm@chromium.org>