BACKPORT: FROMLIST: drm/mediatek: Add mt8195 DisplayPort driver
This patch adds a DisplayPort driver for the Mediatek mt8195 SoC and a
according phy driver mediatek-dp-phy.

It supports both functional units on the mt8195, the embedded
DisplayPort as well as the external DisplayPort units. It offers
hot-plug-detection, audio up to 8 channels, and DisplayPort 1.4 with up
to 4 lanes.

The driver creates a child device for the phy. The child device will
never exist without the parent being active. As they are sharing a
register range, the parent passes a regmap pointer to the child so that
both can work with the same register range. The phy driver sets device
data that is read by the parent to get the phy device that can be used
to control the phy properties.

This driver is based on an initial version by
Jason-JH.Lin <jason-jh.lin@mediatek.com>.

(am from https://patchwork.freedesktop.org/patch/462698)
[fix build error]
SORTTAB vmlinux
SYSMAP System.map
OBJCOPY arch/arm64/boot/Image
MODPOST modules-only.symvers
ERROR: modpost: "mtk_dp_driver"
[drivers/gpu/drm/mediatek/mediatek-drm.ko] undefined!
make[2]: ***
[/mnt/host/source/src/third_party/kernel/v5.10/scripts/Makefile.modpost:124:
modules-only.symvers] Error 1
make[2]: *** Deleting file 'modules-only.symvers'
make[2]: Target '__modpost' not remade because of errors.
make[1]: ***
[/mnt/host/source/src/third_party/kernel/v5.10/Makefile:1418: modules]
Error 2

BUG=b:205808556
TEST=Boot to home.

Signed-off-by: Jitao Shi <jitao.shi@mediatek.com>
Signed-off-by: Markus Schneider-Pargmann <msp@baylibre.com>
Signed-off-by: Guillaume Ranquet <granquet@baylibre.com>
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Tinghan Shen <tinghan.shen@mediatek.com>

Change-Id: I48b08998b55392d119303bf07e7e020334d69a41
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3292854
Reviewed-by: Tzung-Bi Shih <tzungbi@chromium.org>
Tested-by: Tzung-Bi Shih <tzungbi@chromium.org>
Commit-Queue: Tzung-Bi Shih <tzungbi@chromium.org>