BACKPORT: FROMLIST: drm/mediatek: add ETHDR support for MT8195
ETHDR is a part of ovl_adaptor.
ETHDR is designed for HDR video and graphics conversion in the external
display path. It handles multiple HDR input types and performs tone
mapping, color space/color format conversion, and then combine
different layers, output the required HDR or SDR signal to the
subsequent display path.

Signed-off-by: Nancy.Lin <nancy.lin@mediatek.com>
Reviewed-by: Chun-Kuang Hu <chunkuang.hu@kernel.org>
(am from https://patchwork.kernel.org/patch/12623991/)
(also found at https://lore.kernel.org/r/20211117085919.28691-18-nancy.lin@mediatek.com)

[fix buildtest fail]
>   CHK     kernel/kheaders_data.tar.xz
>   LD [M]  drivers/gpu/drm/mediatek/mediatek-drm.o
> ld.lld: error: duplicate symbol: init_module
> >>> defined at mtk_drm_drv.c
> >>>            drivers/gpu/drm/mediatek/mtk_drm_drv.o:(init_module)
> >>> defined at mtk_ethdr.c
> >>>            drivers/gpu/drm/mediatek/mtk_ethdr.o:(.init.text+0x0)
>
> ld.lld: error: duplicate symbol: cleanup_module

BUG=b:188612925
TEST=emerge-cherry sys-kernel/chromeos-kernel-5_10

Signed-off-by: Tinghan Shen <tinghan.shen@mediatek.com>
Change-Id: I7c4ce648527dc6e58f57afa8e298cef2347c2b8d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3255026
Reviewed-by: Tzung-Bi Shih <tzungbi@chromium.org>
Tested-by: Tzung-Bi Shih <tzungbi@chromium.org>
Commit-Queue: Tzung-Bi Shih <tzungbi@chromium.org>