FROMGIT: drm/msm/dp: fix missing #include
Some randconfig builds fail when drm/drm_bridge.h is not included
implicitly in this file:

drivers/gpu/drm/msm/dp/dp_parser.c:279:25: error: implicit declaration of function 'devm_drm_panel_bridge_add' [-Werror,-Wimplicit-function-declaration]
        parser->panel_bridge = devm_drm_panel_bridge_add(dev, panel);

Fixes: 4b296d15b355 ("drm/msm/dp: Allow attaching a drm_panel")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20211026083254.3396322-1-arnd@kernel.org
Signed-off-by: Rob Clark <robdclark@chromium.org>
(cherry picked from commit 02d44fde976a8e9330f855fc535180727c779b9b
 https://gitlab.freedesktop.org/drm/msm.git msm-next)

BUG=b:201590452, b:177187240
TEST=emerge-herobrine chromeos-kernel-5_10

Signed-off-by: Stephen Boyd <swboyd@chromium.org>
Change-Id: I9cd423d45fcc2e0bc77c5cfd06014749e16d90ab
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3253995
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Rob Clark <robdclark@chromium.org>