Revert "FIXUP: UPSTREAM: KVM: x86: Use __try_cmpxchg_user() to emulate atomic accesses"
This reverts commit 64ab739968cf4ae08aca156931ba33179d7a74d4.

Reason for revert: Fix build error:
ld: arch/x86/kvm/x86.o:(__ex_table+0xb0): undefined reference to
`EX_TYPE_EFAULT_REG'
ld: arch/x86/kvm/x86.o:(__ex_table+0xbc): undefined reference to
`EX_TYPE_EFAULT_REG'
ld: arch/x86/kvm/x86.o:(__ex_table+0xc8): undefined reference to
`EX_TYPE_EFAULT_REG'
ld: arch/x86/kvm/x86.o:(__ex_table+0xd4): undefined reference to
`EX_TYPE_EFAULT_REG'

BUG=b:242431919
TEST=CQ

Change-Id: Iac7d595a2b9ca84cbb806d95e9f60de9a8aea812
Signed-off-by: Zubin Mithra <zsm@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4376817
Commit-Queue: Zubin Mithra <zsm@chromium.org>
Tested-by: Zubin Mithra <zsm@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>